# Generated by Django 4.1 on 2022-09-07 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slotId', models.IntegerField()),
                ('playerChoose', models.IntegerField()),
                ('uniqueKey', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=50)),
                ('dateAdded', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
