# Generated by Django 4.1 on 2022-09-07 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='players',
            new_name='player',
        ),
    ]
